---
- name: Setup Linux system
  become: true
  hosts: all
  tasks:
    - name: Basic setup
      ansible.builtin.include_tasks:
        file: basic-setup.yaml

    - name: Install Docker
      ansible.builtin.include_tasks:
        file: install-docker-{{ ansible_os_family | lower }}.yaml

    - name: Install Nala
      when: ansible_os_family == 'Debian'
      ansible.builtin.include_tasks:
        file: install-nala.yaml
