name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
    ANSIBLE_HOSTS_FILE: ${{ secrets.ANSIBLE_HOSTS_FILE }}
    ANSIBLE_SSH_PRIVATE_KEY_FILE: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY_FILE }}

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Install Ansible
      run: |
          python -m pip install --upgrade pip
          pip install --upgrade ansible
          sudo apt install sshpass ansible -y

    - name: Set Environment Variables
      run: |
          mkdir inventory
          echo $ANSIBLE_HOSTS_FILE | base64 -d > inventory/hosts
          echo $ANSIBLE_SSH_PRIVATE_KEY_FILE | base64 -d > ansible_key
          chmod 600 ansible_key

    - name: Run Ansible
      run: |
          ansible-playbook run.yaml
